* stepmake/configure: * configure: Regenerate.

diff --git a/stepmake/configure b/stepmake/configure
--- a/stepmake/configure
+++ b/stepmake/configure
@@ -805,7 +805,6 @@ done
 test -n "$MAKE" || MAKE="no"
 
     
-    #if test "`eval echo '$'"MAKE"`" = "no"; then
     
     r="`eval echo '$'"MAKE"`"
     if test -n "$r" -a "$r" != "error" -a "$r" != "no" && ! expr '`eval echo '$'"MAKE"`' : '.*\(echo\)' > /dev/null; then
@@ -831,6 +830,41 @@ test -n "$MAKE" || MAKE="no"
 	true
     fi
 
+    if test $? -eq 0 -a -n ""; then
+	
+    r="`eval echo '$'"MAKE"`"
+    echo $ac_n "checking "$r version"""... $ac_c" 1>&6
+echo "configure:838: checking "$r version"" >&5
+    exe=`
+    type -p "$r" 2>&1 | awk '{print $NF}'
+`
+    ver=`
+    "$exe" --version 2>&1 | grep -v '^$' | head -1 | awk '{print $NF}'
+`
+    num=`
+    echo "$ver" | awk -F. '
+    {
+      if ($3) {last = $3}
+      else {last =0}
+    }
+    {printf "%s%s%s\n",$1*100, $2*10,last}'
+`
+    req=`
+    echo "" | awk -F. '
+    {
+      if ($3) {last = $3}
+      else {last =0}
+    }
+    {printf "%s%s%s\n",$1*100, $2*10,last}'
+`
+    echo "$ac_t"""$ver"" 1>&6
+    if test "$num" -lt "$req"; then
+	
+    eval "REQUIRED"=\"`eval echo \"'$'REQUIRED\" \""$r  (installed: $ver)"\"`\"
+
+    fi
+
+    fi
 
     
     for ac_prog in find
@@ -838,7 +872,7 @@ do
 # Extract the first word of "$ac_prog", so it can be a program name with args.
 set dummy $ac_prog; ac_word=$2
 echo $ac_n "checking for $ac_word""... $ac_c" 1>&6
-echo "configure:842: checking for $ac_word" >&5
+echo "configure:876: checking for $ac_word" >&5
 if eval "test \"`echo '$''{'ac_cv_prog_FIND'+set}'`\" = set"; then
   echo $ac_n "(cached) $ac_c" 1>&6
 else
@@ -869,7 +903,6 @@ done
 test -n "$FIND" || FIND="no"
 
     
-    #if test "`eval echo '$'"FIND"`" = "no"; then
     
     r="`eval echo '$'"FIND"`"
     if test -n "$r" -a "$r" != "error" -a "$r" != "no" && ! expr '`eval echo '$'"FIND"`' : '.*\(echo\)' > /dev/null; then
@@ -895,6 +928,41 @@ test -n "$FIND" || FIND="no"
 	true
     fi
 
+    if test $? -eq 0 -a -n ""; then
+	
+    r="`eval echo '$'"FIND"`"
+    echo $ac_n "checking "$r version"""... $ac_c" 1>&6
+echo "configure:936: checking "$r version"" >&5
+    exe=`
+    type -p "$r" 2>&1 | awk '{print $NF}'
+`
+    ver=`
+    "$exe" --version 2>&1 | grep -v '^$' | head -1 | awk '{print $NF}'
+`
+    num=`
+    echo "$ver" | awk -F. '
+    {
+      if ($3) {last = $3}
+      else {last =0}
+    }
+    {printf "%s%s%s\n",$1*100, $2*10,last}'
+`
+    req=`
+    echo "" | awk -F. '
+    {
+      if ($3) {last = $3}
+      else {last =0}
+    }
+    {printf "%s%s%s\n",$1*100, $2*10,last}'
+`
+    echo "$ac_t"""$ver"" 1>&6
+    if test "$num" -lt "$req"; then
+	
+    eval "REQUIRED"=\"`eval echo \"'$'REQUIRED\" \""$r  (installed: $ver)"\"`\"
+
+    fi
+
+    fi
 
 
     
@@ -903,7 +971,7 @@ do
 # Extract the first word of "$ac_prog", so it can be a program name with args.
 set dummy $ac_prog; ac_word=$2
 echo $ac_n "checking for $ac_word""... $ac_c" 1>&6
-echo "configure:907: checking for $ac_word" >&5
+echo "configure:975: checking for $ac_word" >&5
 if eval "test \"`echo '$''{'ac_cv_prog_TAR'+set}'`\" = set"; then
   echo $ac_n "(cached) $ac_c" 1>&6
 else
@@ -934,7 +1002,6 @@ done
 test -n "$TAR" || TAR="no"
 
     
-    #if test "`eval echo '$'"TAR"`" = "no"; then
     
     r="`eval echo '$'"TAR"`"
     if test -n "$r" -a "$r" != "error" -a "$r" != "no" && ! expr '`eval echo '$'"TAR"`' : '.*\(echo\)' > /dev/null; then
@@ -960,13 +1027,48 @@ test -n "$TAR" || TAR="no"
 	true
     fi
 
+    if test $? -eq 0 -a -n ""; then
+	
+    r="`eval echo '$'"TAR"`"
+    echo $ac_n "checking "$r version"""... $ac_c" 1>&6
+echo "configure:1035: checking "$r version"" >&5
+    exe=`
+    type -p "$r" 2>&1 | awk '{print $NF}'
+`
+    ver=`
+    "$exe" --version 2>&1 | grep -v '^$' | head -1 | awk '{print $NF}'
+`
+    num=`
+    echo "$ver" | awk -F. '
+    {
+      if ($3) {last = $3}
+      else {last =0}
+    }
+    {printf "%s%s%s\n",$1*100, $2*10,last}'
+`
+    req=`
+    echo "" | awk -F. '
+    {
+      if ($3) {last = $3}
+      else {last =0}
+    }
+    {printf "%s%s%s\n",$1*100, $2*10,last}'
+`
+    echo "$ac_t"""$ver"" 1>&6
+    if test "$num" -lt "$req"; then
+	
+    eval "REQUIRED"=\"`eval echo \"'$'REQUIRED\" \""$r  (installed: $ver)"\"`\"
+
+    fi
+
+    fi
 
 
     if test "x`uname`" = "xHP-UX"; then
 	# Extract the first word of "bash", so it can be a program name with args.
 set dummy bash; ac_word=$2
 echo $ac_n "checking for $ac_word""... $ac_c" 1>&6
-echo "configure:970: checking for $ac_word" >&5
+echo "configure:1072: checking for $ac_word" >&5
 if eval "test \"`echo '$''{'ac_cv_path_BASH'+set}'`\" = set"; then
   echo $ac_n "(cached) $ac_c" 1>&6
 else
@@ -1006,7 +1108,7 @@ fi
 	# Extract the first word of "bash", so it can be a program name with args.
 set dummy bash; ac_word=$2
 echo $ac_n "checking for $ac_word""... $ac_c" 1>&6
-echo "configure:1010: checking for $ac_word" >&5
+echo "configure:1112: checking for $ac_word" >&5
 if eval "test \"`echo '$''{'ac_cv_path_SHELL'+set}'`\" = set"; then
   echo $ac_n "(cached) $ac_c" 1>&6
 else
@@ -1043,7 +1145,7 @@ fi
 	# Extract the first word of "bash", so it can be a program name with args.
 set dummy bash; ac_word=$2
 echo $ac_n "checking for $ac_word""... $ac_c" 1>&6
-echo "configure:1047: checking for $ac_word" >&5
+echo "configure:1149: checking for $ac_word" >&5
 if eval "test \"`echo '$''{'ac_cv_path_BASH'+set}'`\" = set"; then
   echo $ac_n "(cached) $ac_c" 1>&6
 else
@@ -1086,7 +1188,7 @@ do
 # Extract the first word of "$ac_prog", so it can be a program name with args.
 set dummy $ac_prog; ac_word=$2
 echo $ac_n "checking for $ac_word""... $ac_c" 1>&6
-echo "configure:1090: checking for $ac_word" >&5
+echo "configure:1192: checking for $ac_word" >&5
 if eval "test \"`echo '$''{'ac_cv_prog_PYTHON'+set}'`\" = set"; then
   echo $ac_n "(cached) $ac_c" 1>&6
 else
@@ -1117,7 +1219,6 @@ done
 test -n "$PYTHON" || PYTHON="no"
 
     
-    #if test "`eval echo '$'"PYTHON"`" = "no"; then
     
     r="`eval echo '$'"PYTHON"`"
     if test -n "$r" -a "$r" != "error" -a "$r" != "no" && ! expr '`eval echo '$'"PYTHON"`' : '.*\(echo\)' > /dev/null; then
@@ -1143,12 +1244,11 @@ test -n "$PYTHON" || PYTHON="no"
 	true
     fi
 
-#    if ! expr '`eval echo '$'"PYTHON"`' : '.*\(echo\)' > /dev/null; then
-    if test $? -ne 0; then
+    if test $? -eq 0; then
 	# Extract the first word of "python", so it can be a program name with args.
 set dummy python; ac_word=$2
 echo $ac_n "checking for $ac_word""... $ac_c" 1>&6
-echo "configure:1152: checking for $ac_word" >&5
+echo "configure:1252: checking for $ac_word" >&5
 if eval "test \"`echo '$''{'ac_cv_path_PYTHON'+set}'`\" = set"; then
   echo $ac_n "(cached) $ac_c" 1>&6
 else
@@ -1180,6 +1280,41 @@ else
   echo "$ac_t""no" 1>&6
 fi
 
+	if test -n ""; then
+	    
+    r="`eval echo '$'"PYTHON"`"
+    echo $ac_n "checking "$r version"""... $ac_c" 1>&6
+echo "configure:1288: checking "$r version"" >&5
+    exe=`
+    type -p "$r" 2>&1 | awk '{print $NF}'
+`
+    ver=`
+    "$exe" --version 2>&1 | grep -v '^$' | head -1 | awk '{print $NF}'
+`
+    num=`
+    echo "$ver" | awk -F. '
+    {
+      if ($3) {last = $3}
+      else {last =0}
+    }
+    {printf "%s%s%s\n",$1*100, $2*10,last}'
+`
+    req=`
+    echo "" | awk -F. '
+    {
+      if ($3) {last = $3}
+      else {last =0}
+    }
+    {printf "%s%s%s\n",$1*100, $2*10,last}'
+`
+    echo "$ac_t"""$ver"" 1>&6
+    if test "$num" -lt "$req"; then
+	
+    eval "REQUIRED"=\"`eval echo \"'$'REQUIRED\" \""$r  (installed: $ver)"\"`\"
+
+    fi
+
+	fi
     fi
 
 
@@ -1290,7 +1425,7 @@ fi
 
 
     echo $ac_n "checking language""... $ac_c" 1>&6
-echo "configure:1294: checking language" >&5    
+echo "configure:1429: checking language" >&5    
     case "$language" in
       En* | en* | Am* | am* | US* | us*)
 	    lang=English;;
@@ -1325,7 +1460,7 @@ do
 # Extract the first word of "$ac_prog", so it can be a program name with args.
 set dummy $ac_prog; ac_word=$2
 echo $ac_n "checking for $ac_word""... $ac_c" 1>&6
-echo "configure:1329: checking for $ac_word" >&5
+echo "configure:1464: checking for $ac_word" >&5
 if eval "test \"`echo '$''{'ac_cv_prog_MAKEINFO'+set}'`\" = set"; then
   echo $ac_n "(cached) $ac_c" 1>&6
 else
